version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command:
      - "start-dev" # or "start" for production, ensuring you have HTTPS configured
    environment:
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin # Set your desired admin username here
      KEYCLOAK_ADMIN_PASSWORD: admin # Set your desired admin password here
      KEYCLOAK_LOGLEVEL: DEBUG
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - keycloak_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network

networks:
  keycloak_network:
    driver: bridge

volumes:
  postgres_data:
